### ISSUE TITLE
Tab with Google goes blank whenever a link is opened with "open in new tab"

### ISSUE THREAD

**Issue by Shashahan** [dpacassi/disable-javascript#24]

**Comment by Shashahan** [comment]
Whenever i open a link from google with the option "open in new tab" the whole tab with the search goes blank and stays that way until a reload is done.

Firefox 60.0 running on Windows 10 1709
Disable Javascript 2.2.1

**Comment by dpacassi** [comment]
Hi @Shashahan!

Welcome to GitHub and thanks for your report!
I've tried to recreate your bug with the web extension and Firefox 60.0 on Windows 10 but was not able to do so. Also code-wise, I don't see anything that could cause this issue.

Could you try to disable the web extension (Tools -> Add-ons) and check if the issue still exists? If so, the bug must come from another web extension or another program.
Otherwise I would need a screenshot of your Disable JavaScript settings.
Also, what did you search in Google for and which link did you try to open in a new tab?

Thanks for your information!

**Comment by Shashahan** [comment]
This issue can be closed, i found the problem. 

When i disabled the web extension the issue disappears. 
Because you wanted me to provide a screenshot of the settings i opened the settings and saw that the white/blacklist had one an entry with a blank domain field. I wondered if that could be the problem and removed it. 
This was the problem. I have no idea how the entry was created as it seem impossible to create an entry with a blank domain name. 

Thank you very much for your help!

**Comment by dpacassi** [comment]
@Shashahan FYI: I've just created a patch release which now shows grey icons if a page's JS state shouldn't be able to be changed (e.g. new tab, blank url's, etc.).
Your browser should automatically update the web extension in the next 24 hours, thanks for your report and help!
