### ISSUE TITLE
Some sites don't work with extension installed

### ISSUE THREAD

**Issue by v1nsai** [dpacassi/disable-javascript#31]
I've noticed that some sites don't work properly with the extension installed, even with Javascript enabled.  Most recent one I've found is the [Google Translate API signup page.](https://console.cloud.google.com/freetrial?page=0)

With the extension enabled and Javascript switched on, clicking the 'Agree and continue' button does nothing.  With the extension disabled, it works fine.

**Comment by dpacassi** [comment]
Hi @v1nsai!

Thanks for your report! I just checked the site and first also thought that there might be a problem with the web extension.
However, in order to be able to click on the "Agree and continue" button, **you have to accept** the terms and conditions and define if you want to receive email updates first (click on the corresponding radio buttons).

It's a bit confusing that Google does not provide any error message like "Please accept our terms and conditions", so yeah, people can think that something's wrong with the JavaScript.

So unfortunately there's nothing I can do, unless Google hires me to work on their UI ;)

Could you please confirm that this was the issue you've had?
Thanks!

**Comment by v1nsai** [comment]
That was just one example, I've had lots of other websites stop working until I disabled the plugin even though I have allowed all javascript on the page.

I'll leave it on again and find some more examples.

**Comment by dpacassi** [comment]
Closing for now as no additional examples showed up. Feel free to reopen it at any time if it's an issue again, thanks.
