### ISSUE TITLE
Invalid host when entering "37signals.com"

### ISSUE THREAD

**Issue by cgiovanni** [dpacassi/disable-javascript#35]
Hi,

I noticed that I can't add "37signals.com" domain in the domain list using "add" button: it says "please enter a valid host". But the host is valid...

Could you please check?

Thanks

**Comment by dpacassi** [comment]
You're absolutely right, that's a bug in the regex I'm using to verify if the entered input is a valid host.
This will be fixed in a future release!

Please keep in mind that contribution in any form (pull request or [PayPal](https://www.paypal.me/dpacassi/5)) to speed up things are welcome at any time!

**Comment by cgiovanni** [comment]
Hello @dpacassi,

I have just made a donation using PayPal. :-)

Thanks for fixing the issue.

Have a nice day!
